# Simple workflow for deploying frontend to GitHub Pages
name: Deploy Frontend to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - main

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying frontend
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Frontend
        run: |
          cd frontend # navigate to the frontend folder
          npm install
          npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: frontend-build # give a name to the artifact
          path: frontend/build # path to the built frontend
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
        with:
          branch: gh-pages # branch to deploy to (GitHub Pages default)
          folder: frontend/build # folder to deploy from
